### PR TITLE
Make renderWeirdGraphics a pure function (classmethod).

### PR DESCRIPTION
**Pull request by josephlord**

### CODE REVIEW

**Comment by owensd** [comment]
This is not a pure function, you are modifying the input `buffer` within the function. For it to be pure, there needs to be no side-effects. So you need to create a completely new `OffscreenBuffer` instance within `renderWeirdGradient` and return it.

```swift
func RenderWeirdGradient(width: Int, height: Int, blueOffset: Int, greenOffset: Int) -> OffscreenBuffer {
    var buffer = OffscreenBuffer()
    buffer.width = width
    buffer.height = height
    
    let black = Pixel(red: 0, green: 0, blue: 0, alpha: 255)
    buffer.pixels = [Pixel](count: buffer.width * buffer.height, repeatedValue: black)
    
    for var y = 0, height = buffer.height; y < height; y++ {
        let row = y * buffer.width
        for var x = 0, width = buffer.width; x < width; x++ {
            let pixel = Pixel(
                red: 0,
                green: Byte((y + greenOffset) & 0xFF),
                blue: Byte((x + blueOffset) & 0xFF),
                alpha: 255)
            
            buffer.pixels[row + x] = pixel
        }
    }
    
    return buffer
}
```

This method has no speed up in debug or release mode.

**Comment by josephlord** [comment]
Not sure where you got that version from. The PR has this version:
```swift
    final class func renderWeirdGradient(var buffer: OffscreenBuffer, _ blueOffset: Int, _ greenOffset: Int)->OffscreenBuffer {
        for var y = 0; y < buffer.height; y++ {
            let row = y * buffer.width
            for var x = 0; x < buffer.width; x++ {
                // Simply using the "FAST" code block changes the timing from 1.2s
                // per call to 0.37s per call.
                
                // ---- SLOW CODE BLOCK
                // buffer.pixels[row + x].green = Byte((y + greenOffset) & 0xFF)
                // buffer.pixels[row + x].blue = Byte((y + blueOffset) & 0xFF)
                // ---- END SLOW CODE BLOCK
                
                // ---- FASTER CODE BLOCK
                let pixel = Pixel(
                    red: 0,
                    green: Byte((y + greenOffset) & 0xFF),
                    blue: Byte((x + blueOffset) & 0xFF),
                    alpha: 255)
                
                
                buffer.pixels[row + x] = pixel
                // ---- END FASTER CODE BLOCK
            }
        }
        return buffer
        
    }
```

**Comment by owensd** [comment]
That example is what the pure version would look like. Your version modifies the buffer as an input.

**Comment by josephlord** [comment]
No, that would be inout. Using `var` in the function declaration just makes the argument a variable rather than a constant. With structs (and enums) it is still pass by value.
```swift
func f(var a:Int) {
  a = a + 5
  println(a)
}
var i = 10
f(10)
println(i)
// Will print:
// 15
// 10
```

**Comment by owensd** [comment]
Right, var just creates the copy for you, but you need to be careful because if you have any members that are classes, you’ve potentially created side effects.

```swift
class Bar {
    var name: String = "Bar"
}

struct Foo {
    var number: Int
    var numbers: [Int]
    var bar: Bar
}

func g(var foo: Foo) -> Foo {
    // no side-effects, var just copies it
    foo.number = 100
    foo.numbers[1] = 10
    
    // side-effect with var
    foo.bar.name = "g"
    return foo
}

var foo = Foo(number: 12, numbers: [1, 2, 3], bar: Bar())
g(foo)
foo
```

If I changed pixels to be a class type later in my program for performance reasons, you are now potentially overriding the input value.

**Comment by josephlord** [comment]
Fair enough, if it did change from a struct to an object it would definitely change the semantics. I just used the CoW variable as a shortcut to initialising the struct with a fully populated correctly sized buffer.

Structs and copying structs are very fast, much faster than you might expect so I'm not sure how often using objects will speed things up. I don't think objects should ever be chosen for performance reasons but only when you explicitly want reference semantics.

**Pull request closed without merging**
