### PR TITLE
Make the buffer final.

### PR DESCRIPTION
**Pull request by josephlord**

### CODE REVIEW

**Comment by owensd** [comment]
Yeah, that doesn't make really any difference at all. It goes from about 0.37s to about 0.35s in debug.

**Comment by josephlord** [comment]
You need to try it in release. About 7x improvement in my testing.

**Comment by josephlord** [comment]
Added this to your class because I wanted to see the difference in assembly produced. It is quite dramatic.

```swift
    var nonFinalInt = 0
    final var finalInt = 0

    func testFinalAccess() {
        finalInt = finalInt + 77
    }
    
    func testNonFinalAccess() {
        nonFinalInt = finalInt + 88
    }
```

screen shot 2015-01-30 at 16 48 46

screen shot 2015-01-30 at 16 50 52

**Comment by owensd** [comment]
The timing on release with `var buffer = OffscreenBuffer()` is 0.0184s.
The timing on release with `final var buffer = OffscreenBuffer()` is 0.0114s.

That does get us pretty closer to the native performance, but still off by about 0.02s (from this morning's benchmarks).

That's not a 7x increase, and it does nothing for debug, which is still atrociously bad. And yes, the assembly is vastly different because the compiler knows that it cannot be overridden.

**Comment by josephlord** [comment]
Interesting. These are the timings I get starting at your badperf branch. This is the array version not the unsafe buffer version.. I've got a late 2013 Retina MBP with the i7 core. Compiler setting for both is -O (Fastest). 

Note that your optimisation namings in your blog are not the ones for the Swift compiler which has -ONone (None/Debug), -O (Fastest) and -OUnchecked (Fastest/Unchecked) which doesn't do bounds checking and only gives a slight boost beyond -O.

Non-Final: 
elapsed: 0.0223959840077441
elapsed: 0.0179101160028949
elapsed: 0.0174251740099862
elapsed: 0.0180007939925417
elapsed: 0.0180921319988556
elapsed: 0.018994415004272

Final (Note the additional leading zero I have on these)
elapsed: 0.00351828100974672
elapsed: 0.00267002897453494
elapsed: 0.0027174059941899
elapsed: 0.00328351100324653
elapsed: 0.00271164198056795

**Comment by owensd** [comment]
Right, I simply labeled the Swift options incorrectly. I’m using -Onone and -O for debug and release, respectively.

You must have changed something else, that one line does not have that impact. What version of Xcode are you using? I have Version 6.1.1 (6A2008a). Also, the latest version under day005_badperf has the class and members marked as final.

**Comment by josephlord** [comment]
If either the class or the buffer is final you get the speedup I was talking about. If you remove final from both in your latest day5_badperf you will see there is a significant difference (which was what adding final did at the time I branched from your code). The finals on the buffer and offsets are implied by the class being final.

BTW it won't make much of a performance difference but will let you have constants for x and y rather than variables if you do this:
```swift
        let width = buffer.width
        for y in 0..<buffer.height {
            let row = y * width
            for x in 0..<width {
```
With the final in how does it compare to your objective C in release build?

**Comment by owensd** [comment]
I moved the height/width out, it shaves a bit off of the debug mode speed. When I tried the range, it was significantly slower than the imperative for-loop.

With the final keyword, the release performance between the ObjC and the Swift versions are essentially the same. It’s the debug builds that are orders of magnitudes different. I’m not claiming that Swift is slow, I’m claiming that it’s nearly impossible to build and effectively debug computationally complex Swift programs because the debug builds are so slow.

**Comment by josephlord** [comment]
Fair enough, it definitely makes it a nuisance but still luxury compared to some development environments I've used in the past (e.g. embedded TV software).

There are also ways to work around it if you need to, e.g. enable lower framerate and that sort of thing when doing debug but mostly use release. And keep the computationally expensive stuff in a module that you can always build release (and debug the hard way) while most of your other code can run as a debug build.

The Swift team have said that they are working on improving the speed in Debug but in some cases it is always going to be infinitely slower where the release build can just eliminate dead code or unroll loops. 

I assume you saw the [HN discussion](https://news.ycombinator.com/item?id=8970877).

**Pull request closed without merging**
